# Generated by Django 3.1.5 on 2021-02-13 19:44

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210203_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='my cat', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
