# Generated by Django 3.1.5 on 2021-04-11 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysite',
            name='description',
            field=models.TextField(default='test'),
        ),
        migrations.AlterField(
            model_name='mysite',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
