# Generated by Django 3.1.5 on 2021-04-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_auto_20210411_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysite',
            name='last_time_check',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
