# Generated by Django 3.1.5 on 2021-04-11 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0004_auto_20210411_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='checksite',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checks.mysite'),
        ),
    ]
