# Generated by Django 3.1.5 on 2021-03-12 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20210312_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='categ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.cat'),
        ),
    ]
