# Generated by Django 3.1.5 on 2021-03-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20210312_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
