# Generated by Django 3.1.5 on 2021-04-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_city_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
    ]
